services:
  journeyapp.webapi:
    build:
      context: .
      dockerfile: JourneyApp.WebApi/Dockerfile
    image: journeyapp.webapi
    ports:
      - "8080:8080"
    depends_on:
      - "journeyapp.database"
      - "minio"
    volumes:
      - /etc/letsencrypt/live/journey-pet-app.duckdns.org/certificate.pfx:/app/certificate.pfx:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  journeyapp.database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=journeyapp
    volumes:
      - journeyapp.pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=flywotbl@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=Wertyqin923134
    ports:
      - "8081:80"
    depends_on:
      - "journeyapp.database"
    volumes:
      - pgadmin:/var/lib/pgadmin
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"      # API port
      - "9001:9001"      # Console port
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  journeyapp.pgdata:
  pgadmin:
  minio_data: